/* Automatically generated by 'build/bin/build-entry.js' */
import DragMenu from 'packages/drag-menu/index.js';
import NavTab from 'packages/nav-tab/index.js';

const components = [DragMenu, NavTab];

const install = Vue => {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.4',
  install,
  DragMenu,
  NavTab,
};
